# Generated by Django 3.1.4 on 2021-02-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Hire_Date', models.DateTimeField()),
                ('Term_Date', models.DateTimeField()),
                ('Status', models.CharField(choices=[('pending', 'pending'), ('hired', 'hired'), ('terminated', 'terminated')], default='pending', max_length=14)),
                ('EVR', models.CharField(max_length=14)),
                ('Notes', models.TextField()),
                ('Phone', models.IntegerField()),
                ('DOB', models.DateTimeField()),
                ('City', models.CharField(max_length=24)),
                ('Address', models.TextField()),
                ('State', models.CharField(max_length=36)),
                ('Zip', models.CharField(max_length=14)),
                ('License', models.CharField(max_length=24)),
                ('License_State', models.CharField(max_length=14)),
                ('SSN', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IFTA', models.IntegerField()),
                ('Date_placed', models.DateTimeField()),
                ('Truck', models.IntegerField()),
                ('Status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='inactive', max_length=14)),
                ('Year', models.IntegerField()),
                ('Make', models.CharField(max_length=24)),
                ('Model', models.CharField(max_length=24)),
                ('GVWR', models.IntegerField()),
                ('VIN', models.CharField(max_length=24)),
                ('License_Plate', models.IntegerField()),
                ('License_Plate_State', models.CharField(max_length=9)),
                ('Leased_or_Owned', models.CharField(choices=[('leased', 'leased'), ('owned', 'owned')], default='leased', max_length=14)),
                ('ELD', models.CharField(max_length=24)),
            ],
        ),
    ]
