# Generated by Django 3.1.4 on 2021-02-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='DOB',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='driver',
            name='EVR',
            field=models.CharField(choices=[('done', 'done'), ('partial', 'partial'), ('not started', 'not started')], default='not started', max_length=14),
        ),
        migrations.AlterField(
            model_name='driver',
            name='Hire_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='driver',
            name='Term_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='Date_placed',
            field=models.DateField(),
        ),
    ]
